title: Rakugo Project
email: jeremi360@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Rakugo for Godot Engine, Inspired by Ren'Py, Rakugo Project is aimed at providing a better toolset for narrative-based games on Godot.
  Simplify your project, if it is a visual novel, point and click, RPG, interactive text game or many other styles and blends of styles.
  Now its a set of plugins for Godot, that can be used in any Godot project.
  But they are also Kits that bring together of our plugins to template that fit your project genre.

twitter_username: BiernackiJeremi
github_username: rakugoteam
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
highlighter: rouge

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Warsaw

include:
  - _pages
  - _devlog
  - _addons
  - _kits

exclude:
  - "_addons/addon-example.md"
  - "_kits/kit-example.md"
  - "_showcase/showcase-example.md"

# Plugins
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# to make it work on GitHub:
whitelist:
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name: Rakugo Team
  avatar: "/assets/logo.png"
  links:
    - label: "Roadmaps"
      icon: "fas fa-road"
      url: "https://github.com/rakugoteam/Rakugo/projects"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/rakugoteam/Rakugo"
    # - label: "Docs"
    #   icon: "fas fa-book"
    #   url: "https://rakugodocs.readthedocs.io"
    - label: "Discord"
      icon: "fas fa-comments"
      url: "https://discord.gg/K9gvjdg"
    - label: "Patreon"
      icon: "fas fa-donate"
      url: "https://www.patreon.com/rakguoteam"
    - label: "itch.io"
      icon: "fas fa-shopping-bag"
      url: "https://jeremi360x.itch.io/rakugo"
    # - label: "Youtube Channel"
    #   icon: "fab fa-youtube-square"
    #   url: "https://www.youtube.com/channel/UCuItFHsERbsyi8gLJ7Ti1KA"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BiernackiJeremi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rakugoteam/Rakugo"

defaults:
  ##_pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  ##_devlog
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  ##_addons
  - scope:
      path: ""
      type: addons
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
  ##_downloads
  - scope:
      path: ""
      type: kits
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true

# Collections
collections:
  addons:
    output: true
    permalink: /:collection/:path/
  kits:
    output: true
    permalink: /:collection/:path/
  showcase:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
