# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rakugo Project
email: jeremi360@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Rakugo for Godot Engine, Inspired by Ren'Py, Rakugo Project is aimed at providing a better toolset for narrative-based games on Godot.
  Simplify your project, if it is a visual novel, point and click, RPG, interactive text game or many other styles and blends of styles.
  Now its a set of plugins for Godot, that can be used in any Godot project.
  But they are also Kits that bring together of our plugins to template that fit your project genre.

twitter_username: BiernackiJeremi
github_username: rakugoteam
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Warsaw

include:
  - _pages
  - _posts
  - _addons
  - _downloads

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# to make it work on GitHub:
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name: Rakugo Team / Jeremi Biernacki
  avatar: "/assets/imgs_main/logo.png"
  links:
    - label: "Roadmaps"
      icon: "fas fa-road"
      url: "https://github.com/rakugoteam/Rakugo/projects"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/rakugoteam/Rakugo"
    # - label: "Docs"
    #   icon: "fas fa-book"
    #   url: "https://rakugodocs.readthedocs.io"
    - label: "Discord"
      icon: "fas fa-comments"
      url: "https://discord.gg/K9gvjdg"
    - label: "Patreon"
      icon: "fas fa-donate"
      url: "https://www.patreon.com/rakguoteam"
    - label: "itch.io"
      icon: "fas fa-shopping-bag"
      url: "https://jeremi360x.itch.io/rakugo"
    # - label: "Youtube Channel"
    #   icon: "fab fa-youtube-square"
    #   url: "https://www.youtube.com/channel/UCuItFHsERbsyi8gLJ7Ti1KA"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BiernackiJeremi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rakugoteam/Rakugo"

defaults:
  ##_pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  ##_posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  ##_addons
  - scope:
      path: "_addons"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
  ##_downloads
  - scope:
      path: "_downloads"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
